Traceback (most recent call last):
  File "/home/kishore/LearnPY/tracebackinfointxt.py", line 3, in <module>
    raise Exception('This is the error message')
Exception: This is the error message
